### PR TITLE
CiviCRM compatible fixes and improvements for Mosaico library v0.18.9 

### PR DESCRIPTION
**Pull request by monishdeb**

### CODE REVIEW

**Comment by monishdeb** [comment]
PR contains porting the CiviCRM compatibility fixes and improvements from the previous version.  

ping @mattwire @deepak-srivastava @seamuslee001

**Comment by monishdeb** [comment]
To test the fixes/improvements in this PR, please use this attached tarball [mosaico.zip](https://github.com/civicrm/mosaico/files/10733603/mosaico.zip) Instructions are mentioned [here](https://github.com/civicrm/mosaico/pull/14#issuecomment-1427419080)

**Comment by deepak-srivastava** [comment]
@monishdeb 
[template-loader - Allow Civi tokens to be used in HREF](https://github.com/civicrm/mosaico/pull/15/commits/db018c1391b032339068608b32d060527affc00e) - I'm able to use links with token even without the patch. Something might have improved there. Think this can go away, unless you able to test and see it's effect.

I'm unable to notice any difference/effect with following ones. Think they can go away as well, unless you/someone able to test and see their effect.
- [Improve the ext droppable interaction with large images by switching](https://github.com/civicrm/mosaico/pull/15/commits/5724e62ce90bb85cdde4b62111a12ac58e671131) 
- [Show preview text, show error message on subsequent invalid image upload](https://github.com/civicrm/mosaico/pull/15/commits/01a0165bf9e8e83e0af933d25a36a90608987d9e)


Rest looks fine to me.

@mattwire just a note that this PR needs to go in a new branch when ready - "v0.18.9-civicrm-1".

Thanks,
Deepak

**Comment by mattwire** [comment]
I've created the new branch and updated this PR to point to it.

**Comment by deepak-srivastava** [comment]
Hi @monishdeb, any comments on https://github.com/civicrm/mosaico/pull/15#issuecomment-1431368868?

**Comment by monishdeb** [comment]
@deepak-srivastava sorry for the delay. Thank you for your feedback, and yes I agree with all the points. I will exclude [template-loader - Allow Civi tokens to be used in HREF](https://github.com/civicrm/mosaico/pull/15/commits/db018c1391b032339068608b32d060527affc00e) commit as I am not able to find the ticket or code that resolved this issue but can confirm its no longer an issue in the latest library. About the other commits, I am still working on the fix, and its time taking time. I'll let you know once I update the PR. Meantime marking with WIP.

**Comment by deepak-srivastava** [comment]
@monishdeb If it's going to take long, shall we push the ones we sure about, first? And rest in the other PRs?

**Comment by monishdeb** [comment]
@deepak-srivastava sorry for the delay I have excluded those commits from this PR to get it merged and will submit a separate PR for those two remaining issues.

**Comment by deepak-srivastava** [comment]
Thanks @monishdeb. 

@mattwire this is good to merge.

**Pull request merged**
