### PR TITLE
Merge with latest Mosaico V0.18.9

### PR DESCRIPTION
**Pull request by monishdeb**

### CODE REVIEW

**Comment by monishdeb** [comment]
Recipe to test the Mosaico library : 

## Using tarball : 
- go to your uk.co.vedaconsulting.mosaico extension directory 
- replace the mosaico library with the after downloading >> extrating the attached tarball in packages directory. 
```shell
$ cd  <mosaico-ext-directory>/packages/
$ rm -rf mosaico
$ wget https://github.com/civicrm/mosaico/files/10719226/mosaico.tar.gz
$ tar -xvf mosaico.tar.gz
```
That's it. Test the mosaico installation into your civicrm-site setup.

Attached tarball - [mosaico.tar.gz](https://github.com/civicrm/mosaico/files/10719226/mosaico.tar.gz)
   
## Using patch : 
- Git clone the patched mosaico library repo  and generate tarball
```shell
 $ git clone https://github.com/JMAConsulting/mosaico.git 
 $ cd <mosaico dir>
 $ git checkout origin/v0.18.9-civicrm -b v0.18.9-civicrm // switch to the branch that contains the v0.18.9 patched file
 $ npm install // not necessary but ensure all the dependencies were resolved
 $ grunt build  // build the tarball
 ```
 - Replace the mosaico extension mosaico library directory with the generated tarball
 ```shell
 $ cp -r dist/rs/* <path to uk.co.vedaconsulting.mosaico>/packages/mosacio/dist/*  //update the dist dir of extension with the one built in previous step
 ```
 -  Update the template directory
 ```shell
 $ cp -r templates/* <path to uk.co.vedaconsulting.mosaico>/packages/mosacio/templates/*
 ```
 That's it. Test the mosaico installation into your civicrm-site setup.

**Comment by mountev** [comment]
@monishdeb I tested on drupal & wordpress so far. Found one issue so far:

The placeholder url is supposed to be for backend with permissions (not public).
The placeholder images are being generated as civicrm/mosaico/img?method=placeholder&..
whereas it should be something like civicrm/mosaico/img/placeholder?method=placeholder&..

In earlier version the patch looked something like this - https://github.com/civicrm/mosaico/commit/bdbdf2ecf41c50fe046e7d276479b0d563177cf4

I'll update if I find anything with more testing (including Joomla)

We could keep the master same as voidlab and create a new branch sth like "0.18.9-civicrm1" for additional set of changes for making the library fully functional/compatible with civi. This will also help with keeping track of additional set of changes for library, like it was done for "v0.15-civicrm-2" branch. 
So we might have to remove any adjustment commits from this PR. Like this one - https://github.com/civicrm/mosaico/pull/14/commits/87637a1cc24e19fcd0ee3b83d3ef5b4d87669189, and submit into the branch PR.

I think the master changes (latest voidlab) should be merged anyway asap. so next set of changes could come in.

cc: @mattwire

**Comment by deepak-srivastava** [comment]
[@monishdeb](https://github.com/monishdeb) I tested on drupal & wordpress so far. Found one issue so far:

The placeholder url is supposed to be for backend with permissions (not public).
The placeholder images are being generated as civicrm/mosaico/img?method=placeholder&..
whereas it should be something like civicrm/mosaico/img/placeholder?method=placeholder&..

In earlier version the patch looked something like this - [bdbdf2e](https://github.com/civicrm/mosaico/commit/bdbdf2ecf41c50fe046e7d276479b0d563177cf4)

I'll update if I find anything with more testing (including Joomla)

We could keep the master same as voidlab and create a new branch sth like "0.18.9-civicrm1" for additional set of changes for making the library fully functional/compatible with civi. This will also help with keeping track of additional set of changes for library, like it was done for "v0.15-civicrm-2" branch.
So we might have to remove any adjustment commits from this PR. Like this one - [87637a1](https://github.com/civicrm/mosaico/commit/87637a1cc24e19fcd0ee3b83d3ef5b4d87669189), and submit into the branch PR.

I think the master changes (latest voidlab) should be merged anyway asap. so next set of changes could come in.

cc: [@mattwire](https://github.com/mattwire)

**Comment by francescbassas** [comment]
Just tested. Nothing has broken and apparently everything still works. I have noticed that the interface is now translated into Spanish.

**Comment by monishdeb** [comment]
Thank you @deepak-srivastava and @francescbassas for your feedback. I'll fix the placeholder url and yes I agree to have a separate branch to `0.18.9-civicrm-1` for the additional fixes. I have dropped the last commit [87637a1](https://github.com/civicrm/mosaico/commit/87637a1cc24e19fcd0ee3b83d3ef5b4d87669189) and I think this current PR can be merged now. I will address the placeholder issue and style fix in a separate PR.

**Comment by monishdeb** [comment]
@deepak-srivastava @mattwire I have created a separate branch and cherry-picked commits (to port the previous improvements and compatible fixes) and additional fixes in it. Here's the compare link https://github.com/JMAConsulting/mosaico/compare/v0.18.9-civicrm...JMAConsulting:mosaico:v0.18.9-civicrm-1?expand=1

Can you please merge this PR (that simply holds the v0.18.9 upgrade)? I will submit a new PR for all the additional sets of CiviCRM compatible changes.

**Pull request merged**
